# -*- coding: utf-8 -*-
"""DangQuocThai_ConnectLinkedIn

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12yI9gid3zExhOyT7bhB8JMMJy1PvzThj

# **CÀI ĐẶT THƯ VIỆN CẦN THIẾT**
"""
import os
import time
import google_colab_selenium as gs
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.remote.webelement import WebElement
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException, TimeoutException
from PIL import Image as PILImage
from IPython.display import Image as DispImage, display

"""# **HÀM HỖ TRỢ**"""

def display_full_screenshot(driver):
    # Wait for the body element to be present
    WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.TAG_NAME, "body")))

    # Lấy chiều cao của trang (toàn bộ nội dung)
    total_height = driver.execute_script("return document.body.scrollHeight")

    # Điều chỉnh chiều cao của cửa sổ trình duyệt để khớp với chiều cao của trang
    driver.set_window_size(1920, total_height)  # Đặt chiều rộng và chiều cao mong muốn

    # Chụp ảnh màn hình
    driver.save_screenshot('screenshot.png')

    # Hiển thị ảnh chụp màn hình
    time.sleep(2)  # Đợi ảnh được lưu
    display(DispImage('screenshot.png'))

"""# **KẾT NỐI GOOGLE SHEETS**"""

import pickle
import pandas as pd
import requests
import pandas as pd
from google.colab import auth
from google.auth import default
from googleapiclient.discovery import build

# AUTHENTICATE.
auth.authenticate_user()
creds, _ = default()
# CREATE THE SERVICE.
service = build('sheets', 'v4', credentials=creds)
# SPREEDSHEET GỐC.
SPREADSHEET_ID = '1sgBi2o7wvi-fmMdu-CRqREyV1J3KKgKXkn9bbM9Qjno'
# RANGE GỐC.
RANGE_NAME = 'Sheet1!A:E'
# CALL GOOGLE SHEETS API.
sheet = service.spreadsheets()
result = sheet.values().get(spreadsheetId=SPREADSHEET_ID, range=RANGE_NAME).execute()
values = result.get('values', [])
# ENSURE ALL ROWS HAVE THE SAME NUMBER OF COLUMNS.
max_cols = max(len(row) for row in values)
values = [row + [''] * (max_cols - len(row)) for row in values]
# CONVERT TO DATAFRAME.
df = pd.DataFrame(values[1:], columns=values[0])
# FILL ALL NAN WITH AN EMPTY STRING.
df = df.fillna('')

"""# **HIỂN THỊ KẾT QUẢ GOOGLE SHEETS**"""

options = Options()

options.add_argument('--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36')
options.add_argument("--window-size=1920,1080")
options.add_argument('--headless')
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
options.add_argument('--disable-gpu')

driver = gs.Chrome(options=options)


# options.add_argument('--no-sandbox')
# options.add_argument("--disable-dev-shm-usage")
# options.add_argument('--headless')
# options.add_argument('--disable-gpu')
# options.add_argument("--window-size=1920, 1200")
# options.add_argument('--disable-dev-shm-usage')

# driver = webdriver.Chrome(options=options)

#Test
driver.get("https://www.linkedin.com")
display_full_screenshot(driver)

"""# **HÀM ĐĂNG NHẬP**"""

BASE_PATH = '/content/drive/MyDrive/Colab Notebooks/CMT-Dragon'
COOKIES_FILE = os.path.join(BASE_PATH, 'linkedin_cookies.pkl')
CREDENTIALS_FILE = os.path.join(BASE_PATH, 'linkedin_credentials.pkl')

def login_with_cookies(driver):
    """Đăng nhập sử dụng cookies nếu có"""
    driver.get("https://www.linkedin.com")

    # Kiểm tra nếu cookies tồn tại
    if os.path.exists(COOKIES_FILE):
      print("COOKIES FILE FOUND! LOADING COOKIES...")
      with open(COOKIES_FILE, "rb") as cookies_file:
          cookies = pickle.load(cookies_file)

      for cookie in cookies:
          driver.add_cookie(cookie)

      # Sau khi thêm cookies, làm mới trang để áp dụng
      driver.refresh()
      time.sleep(3)
      return True  # Đăng nhập thành công bằng cookies
    return False

def save_cookies(driver):
    """Lưu cookies vào file"""
    with open(COOKIES_FILE, "wb") as cookies_file:
        pickle.dump(driver.get_cookies(), cookies_file)
    print("INFO: COOKIES SAVED!")

def load_cookies(driver: webdriver.Chrome, file_name: str):
    """Đọc cookies từ file pickle và thêm vào browser"""
    if os.path.exists(file_name):
        with open(file_name, 'rb') as f:
            cookies = pickle.load(f)
            for cookie in cookies:
                driver.add_cookie(cookie)

def load_credentials():
    """Tải thông tin đăng nhập từ file"""
    if os.path.exists(CREDENTIALS_FILE):
        with open(CREDENTIALS_FILE, "rb") as f:
            return pickle.load(f)
    return None

def save_credentials(username, password):
    """Lưu thông tin đăng nhập vào file"""
    with open(CREDENTIALS_FILE, "wb") as f:
        pickle.dump({"username": username, "password": password}, f)

def handle_cookie_acceptance(driver: webdriver.Chrome):
    """Xử lý chấp nhận cookies nếu có"""
    try:
        driver.find_element(By.XPATH, "//button[span[text()='Accept']]").click()
        print("INFO: COOKIES IS ACCEPTED!")
    except:
        print("INFO: COOKIES IS NOT REQUIRED!")

def handle_code_verification(driver: webdriver.Chrome):
    """Xử lý yêu cầu nhập mã xác thực nếu có"""
    try:
        # Tìm trường nhập mã xác thực
        ID_FIELD = "input__email_verification_pin"
        CONDITION = EC.presence_of_element_located((By.ID, ID_FIELD))
        verification_field = WebDriverWait(driver, 20).until(CONDITION)

        # Tìm nút submit
        ID_FIELD = "email-pin-submit-button"
        CONDITION = EC.presence_of_element_located((By.ID, ID_FIELD))
        submit_button = WebDriverWait(driver, 20).until(CONDITION)

        # Nhập mã xác thực
        code = input("Verification code required! Check your email and enter the code: ")
        verification_field.send_keys(code)
        time.sleep(1)
        submit_button.click()
        time.sleep(2)
    except:
        print("INFO: NO VERIFICATION DETECTED!")

def login(driver: webdriver.Chrome, username: str, password: str):
    """Đăng nhập vào LinkedIn với username và password mới nếu có sự thay đổi"""
    XPATH_USERNAME = '//*[@id="username"]'
    XPATH_PASSWORD = '//*[@id="password"]'
    XPATH_LOGIN_BUTTON = '//button[contains(@class, "btn__primary--large") and @aria-label="Sign in"]'

    driver.get("https://www.linkedin.com/login")
    time.sleep(2)  # Ensure the page is fully loaded

    # Cần xử lý chấp nhận ở đây
    handle_cookie_acceptance(driver)

    # Kiểm tra nếu có cookies và kiểm tra xem username, password có thay đổi không
    credentials = load_credentials()

    if os.path.exists(COOKIES_FILE) and credentials:
        # Kiểm tra nếu username hoặc password đã thay đổi
        if credentials['username'] == username and credentials['password'] == password:
            # Tải cookies và thử đăng nhập
            load_cookies(driver, COOKIES_FILE)
            driver.get("https://www.linkedin.com/feed")
            time.sleep(3)

            # Kiểm tra xem đã đăng nhập chưa bằng cách xem có biểu tượng người dùng không
            try:
                user_icon = WebDriverWait(driver, 10).until(
                    EC.presence_of_element_located((By.CLASS_NAME, 'global-nav__me-photo')))
                print("INFO: Logged in using cookies!")
                # display_full_screenshot(driver)
                return
            except:
                print("INFO: Cookies không hợp lệ, thử đăng nhập lại...")

    # Nếu thông tin đăng nhập đã thay đổi hoặc không có cookies, đăng nhập thủ công
    driver.get("https://www.linkedin.com/login")
    username_field = WebDriverWait(driver, 20).until(EC.presence_of_element_located((By.XPATH, XPATH_USERNAME)))
    password_field = WebDriverWait(driver, 20).until(EC.presence_of_element_located((By.XPATH, XPATH_PASSWORD)))
    login_button = WebDriverWait(driver, 20).until(EC.presence_of_element_located((By.XPATH, XPATH_LOGIN_BUTTON)))

    username_field.send_keys(username)
    time.sleep(2)
    password_field.send_keys(password)
    time.sleep(2)
    login_button.click()

    handle_code_verification(driver)

    time.sleep(5)

    # Lưu cookies và thông tin đăng nhập sau khi đăng nhập thành công
    save_cookies(driver)
    save_credentials(username, password)
    print("INFO: Đăng nhập thành công và đã lưu cookies, thông tin đăng nhập!")
    # display_screenshot(driver, "status.png")
    # display_full_screenshot(driver)

from google.colab import drive
drive.mount('/content/drive')

"""# **THỰC HIỆN ĐĂNG NHẬP**"""

username ="ray.lead@sam-foundation.org"
password = "passnotE@1234"

login(driver, username, password)

# import os

# COOKIES_FILE = 'linkedin_cookies.pkl'

# if os.path.exists(COOKIES_FILE):
#     os.remove(COOKIES_FILE)
#     print(f"INFO: Removed {COOKIES_FILE}")
# else:
#     print(f"INFO: {COOKIES_FILE} not found. No cookies to remove.")

display_full_screenshot(driver)

"""# **XPATH VÀ CSS_SELECTOR**"""

# XPATH ỨNG VỚI NÚT CONNECT.
STATUS_CONNECT = "//main//section[1]//a[contains(., 'Connect') or contains(@aria-label, 'Invite')]"

# XPATH ỨNG VỚI NÚT PENDING.
#STATUS_MESSAGE = "/html/body/div[5]/div[3]/div/div/div[2]/div/div/main/section[1]/div[2]/div[3]/div/div[1]/button"
STATUS_PENDING = "//main//section[1]//a[contains(., 'Pending')]"
# XPATH ỨNG VỚI NÚT MORE.
#BUTTON_MORE = "/html/body/div[5]/div[3]/div/div/div[2]/div/div/main/section[1]/div[2]/div[3]/div/div[2]/button"
BUTTON_MORE = "//main//section[1]//button[contains(@aria-label, 'More') or contains(., 'More')]"
DROPDOWN_MENU = "//div[@role='menu']"
# XPATH ỨNG VỚI NÚT CONNECT KHI NHẤN NÚT MORE.
MORE_UNCONNECT = DROPDOWN_MENU + "//div[contains(@aria-label, 'Invite') and contains(@aria-label, 'to connect')]"
# XPATH ỨNG VỚI NÚT UNCONNECT KHI NHẤN NÚT MORE.
MORE_CONNECT = DROPDOWN_MENU + "//div[contains(@aria-label, 'Remove') and contains(@aria-label, 'connection')]"
# XPATH ỨNG VỚI NÚT PENDING KHI NHẤN NÚT MORE.
MORE_PENDING = DROPDOWN_MENU + "//div[contains(@aria-label, 'Withdraw')]"
# XPATH ỨNG VỚI NÚT ADD A NOTE.
BUTTON_ADD_NOTE = "//button[contains(@aria-label, 'Add a note')]"
# XPATH ỨNG VỚI KHUNG NHẬP NOTE.
TEXTAREA_NOTE = "//textarea[@id='custom-message']"
# XPATH ỨNG VỚI NÚT GỬI NOTE.
BUTTON_SEND_NOTE = "//button[@aria-label='Send now']"
# CSS_SELECTOR ỨNG VỚI NÚT GỬI CONNECT MÀ KHÔNG DÙNG NOTE.
BUTTON_SEND_WITHOUT_NOTE = "button[aria-label*='without a note']"
# XPATH ỨNG VỚI NÚT GỬI CONNECT MÀ DÙNG NOTE.
TEXTFIELD_VERIFY_EMAIL = "//input[@id='email'] | //label[contains(., 'email')]/following-sibling::input"
BUTTON_CONFIRM_EMAIL = "//button[@id='email-confirm'] | //button[contains(@aria-label, 'Verify')]"

"""# **HÀM GỬI KẾT NỐI**"""

def check_status(driver: webdriver.Chrome, xpath: str, *kws):
    try:
        element = WebDriverWait(driver, 2).until(EC.presence_of_element_located((By.XPATH, xpath)))
        status_text = element.get_attribute("aria-label") or ""
        inner_text = element.text or ""

        # Gộp cả 2 text lại
        combined_text = status_text + " " + inner_text

        for keyword in kws:
            if keyword.lower() in combined_text.lower():
                print(f"STATUS: {keyword}")
                return True
    except:
      pass
    return False


def check_status_in_more(driver: webdriver.Chrome):
    # CHECK UNCONNECTED STATUS IN MORE.
    if check_status(driver, MORE_UNCONNECT, "Invite", "Connect"):
        return "Unconnected"
    # CHECK CONNECTED STATUS IN MORE.
    if check_status(driver, MORE_CONNECT, "Remove", "connection"):
        return "Connected"
    # CHECK PENDING STATUS IN MORE.
    if check_status(driver, "//div", "Withdraw", "Pending"):
        return "Pending"
    return "Unknown"  # Giá trị trả về mặc định


def find_element_in_list(driver: webdriver.Chrome, e_list: list[str]):
    for e in e_list:
        try:
            return WebDriverWait(driver, 2).until(EC.presence_of_element_located((By.XPATH, e)))
        except:
          continue
    return None

import random
def send_connection(driver: webdriver.Chrome, xpath: str, email: str):
    try:
        # CLICK BUTTON CONNECT.
        try:
            e = WebDriverWait(driver, 5).until(EC.presence_of_element_located((By.XPATH, xpath)))
            e.click()
        except TimeoutException:
            print("ERROR: BUTTON CONNECT NOT FOUND")
            return "Error"
        except Exception as ex:
            print(f"ERROR: FAILED TO CLICK CONNECT BUTTON: {ex}")
            return "Error"

        # CLICK SEND WITHOUT NOTE.
        try:
            # IT'S WRAPPED IN #SHADOW-HOST (OPEN). WE MUST OPEN IT WITH CSS_SELECTOR INSTEAD
            script = """
                const selector = arguments[0]; // Nhận giá trị từ biến BUTTON_SELECTOR
                    const allElements = document.querySelectorAll('*');
                    for (let el of allElements) {
                        if (el.shadowRoot) {
                            const btn = el.shadowRoot.querySelector(selector);
                            if (btn) {
                                btn.click();
                                return "CLICKED_SHADOW";
                            }
                        }
                    }
                    const normalBtn = document.querySelector(selector);
                    if (normalBtn) {
                        normalBtn.click();
                        return "CLICKED_NORMAL";
                    }
                    return "NOT_FOUND";
            """
            result = driver.execute_script(script, BUTTON_SEND_WITHOUT_NOTE)
            if result != "NOT_FOUND":
                print("SUCCESS: SENT CONNECT WITHOUT NOTE!")
                return "Connected"
            return "Connected"
        except TimeoutException:
            email_field = driver.find_elements(By.XPATH, TEXTFIELD_VERIFY_EMAIL)
            if email_field and email:
                email_field[0].send_keys(email)
                time.sleep(random.uniform(1, 2))
                verify_btn = driver.find_element(By.XPATH, BUTTON_CONFIRM_EMAIL)
                verify_btn.click()

                time.sleep(2)

                return "Connected"
            print("ERROR: NO SEND BUTTON FOUND!")
            return "Error"
    except Exception as e:
        print(f"\n {e}")
        return "Error"

def check_connection(driver: webdriver.Chrome, email: str, note: str = None):
    try:
        # CHECK PENDING STATUS.
        if check_status(driver, STATUS_PENDING, "Pending", "Sent"):
            print("STATUS: PENDING")
            return "Pending"

        # CHECK UNCONNECTED STATUS.
        if check_status(driver, STATUS_CONNECT, "Invite", "Connect"):
            status = send_connection(driver, STATUS_CONNECT, email)  # Gửi kết nối không có ghi chú
            print(f"STATUS: {status}")
            return status

        # FIND BUTTON MORE.
        print("CHECKING IN MORE", end=" ")
        try:
            button_more = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, BUTTON_MORE)))
            button_more.click()

            # CHECK MORE MENU
            WebDriverWait(driver, 3).until(EC.presence_of_element_located((By.XPATH, DROPDOWN_MENU)))

            status_in_more = check_status_in_more(driver)
            if status_in_more == "Unconnected":
              return send_connection(driver, MORE_UNCONNECT, email)
            elif status_in_more == "Connected":
              return "Connected"
        except TimeoutException:
            print("ERROR: BUTTON MORE NOT FOUND!")
            return "ERROR: BUTTON MORE NOT FOUND!"

    except Exception as e:
        print(f"ERROR: {e}")
        return "Error"

"""# **THỰC HIỆN GỬI KẾT NỐI**"""

for index, row in df.iterrows():
    # GO TO PROFILE LINK.
    if row['Status'] == 'Unconnected':
        profile_link = row['LinkedIn']
        email = row["Email"]
        print(f"Visiting profile: {profile_link}", end=" ")
        driver.get(profile_link)
        #
        display_full_screenshot(driver)
        status = ""
        # Đợi trang tải đầy đủ trước khi kiểm tra kết nối
        time.sleep(2)

        try:
          # Wait until page loads
          time.sleep(random.uniform(3, 5))
          # Pretend to be reading profile
          print("Reading profile...", end=" ")
          time.sleep(random.uniform(5, 10))
          # Simulate slight scroll down
          driver.execute_script("window.scrollBy(0, 500);")
          time.sleep(random.uniform(2, 5))
          driver.execute_script("window.scrollTo(0, 0);")
          time.sleep(2)
          # CHECK CONNECTION AND SEND WITHOUT NOTE.
          status = check_connection(driver, row["Email"])  # Không gửi ghi chú
        except Exception as e:
          print(f"ERROR: {e}")
          status = "Error"
        df.at[index, 'Status'] = status
        print(f"Status: {status}")
        # SAVE STATUS ON GOOGLE SHEET OF 1 ROW
        sheet.values().update(
            spreadsheetId=SPREADSHEET_ID,
            range=f"Sheet1!C{index + 2}",
            valueInputOption="USER_ENTERED",
            body={"values": [[status]]}
        ).execute()

      # TAKE A BREAK BETWEEN EACH PERSON
        if index < len(df) - 1:
            print("Taking a break...", end=" ")
            driver.get("https://www.linkedin.com")
            time.sleep(random.randint(30, 60))

"""# **KẾT THÚC CHƯƠNG TRÌNH**"""

driver.quit()