# -*- coding: utf-8 -*-
"""DangQuocThai_ConnectLinkedIn

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12yI9gid3zExhOyT7bhB8JMMJy1PvzThj

# **CÀI ĐẶT THƯ VIỆN CẦN THIẾT**
"""
import os
import time
import base64
import pickle
import pandas as pd
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException, NoSuchElementException


def get_local_data():
    file_path = 'data/test_sheet.csv' # Tên file bạn để trong Repo
    if os.path.exists(file_path):
        df = pd.read_csv(file_path)
        # df = pd.read_excel('test_data.xlsx') # Nếu dùng Excel
        print(f"📊 Đã nạp {len(df)} dòng từ file {file_path}")
        return df
    else:
        print("❌ ERROR: Không tìm thấy file dữ liệu!")
        return None
    
def get_cookies_from_env():
    """Lấy cookies đã được mã hóa từ biến môi trường và giải mã nó"""
    encoded_cookies = os.getenv("LINKEDIN_COOKIES")
    if not encoded_cookies:
        print("ERROR: LINKEDIN_COOKIES environment variable not found!")
        return None

    try:
        decoded_bytes = base64.b64decode(encoded_cookies)
        cookies = pickle.loads(decoded_bytes)
        print("INFO: Cookies loaded from environment variable!")
        return cookies
    except Exception as e:
        print(f"ERROR: Failed to decode cookies: {e}")
        return None

def login_with_cookies(driver):
    """Đăng nhập sử dụng cookies nếu có"""
    driver.get("https://www.linkedin.com")
    cookies = get_cookies_from_env()
    if cookies:
        for cookie in cookies:
            if 'sameSite' in cookie:
                del cookie['sameSite']  # Loại bỏ thuộc tính sameSite nếu có
            driver.add_cookie(cookie)
        driver.refresh()
        time.sleep(3)
        print("INFO: Logged in using cookies from environment variable!")
        return True
    return False

def handle_cookie_acceptance(driver: webdriver.Chrome):
    """Xử lý chấp nhận cookies nếu có"""
    try:
        driver.find_element(By.XPATH, "//button[span[text()='Accept']]").click()
        print("INFO: COOKIES IS ACCEPTED!")
    except:
        print("INFO: COOKIES IS NOT REQUIRED!")

def handle_code_verification(driver: webdriver.Chrome):
    """Xử lý yêu cầu nhập mã xác thực nếu có"""
    try:
            # Kiểm tra xem có trường nhập mã không
        WebDriverWait(driver, 5).until(EC.presence_of_element_located((By.ID, "input__email_verification_pin")))
        print("⚠️ CRITICAL: LINKEDIN REQUIRES VERIFICATION. AUTOMATIC LOGIN FAILED!")

        return False 
    except:
        print("INFO: NO VERIFICATION DETECTED!")
        return True

def login(driver: webdriver.Chrome):
    """Đăng nhập vào LinkedIn với username và password mới nếu có sự thay đổi"""
    driver.get("https://www.linkedin.com")
    time.sleep(2)  # Ensure the page is fully loaded

    # Cần xử lý chấp nhận ở đây
    handle_cookie_acceptance(driver)

    cookies = get_cookies_from_env()
    if not cookies:
        return False
    for cookie in cookies:
        if 'sameSite' in cookie:
            del cookie['sameSite']  # Loại bỏ thuộc tính sameSite nếu có
        driver.add_cookie(cookie)
    driver.refresh()
    time.sleep(5)
    print("INFO: Logged in using cookies from environment variable!")
    try:
        WebDriverWait(driver, 15).until(
            EC.presence_of_element_located((By.CLASS_NAME, 'global-nav__me-photo'))
        )
        print("✅ SUCCESS: Đã vào được LinkedIn bằng Cookies!")
        return True
    except:
        print("❌ CRITICAL: Cookie đã hết hạn hoặc bị LinkedIn từ chối.")
        return False


# XPATH ỨNG VỚI NÚT CONNECT.
STATUS_CONNECT = "//main//section[1]//a[contains(., 'Connect') or contains(@aria-label, 'Invite')]"

# XPATH ỨNG VỚI NÚT PENDING.
#STATUS_MESSAGE = "/html/body/div[5]/div[3]/div/div/div[2]/div/div/main/section[1]/div[2]/div[3]/div/div[1]/button"
STATUS_PENDING = "//main//section[1]//a[contains(., 'Pending')]"
# XPATH ỨNG VỚI NÚT MORE.
#BUTTON_MORE = "/html/body/div[5]/div[3]/div/div/div[2]/div/div/main/section[1]/div[2]/div[3]/div/div[2]/button"
BUTTON_MORE = "//main//section[1]//button[contains(@aria-label, 'More') or contains(., 'More')]"
DROPDOWN_MENU = "//div[@role='menu']"
# XPATH ỨNG VỚI NÚT CONNECT KHI NHẤN NÚT MORE.
MORE_UNCONNECT = DROPDOWN_MENU + "//div[contains(@aria-label, 'Invite') and contains(@aria-label, 'to connect')]"
# XPATH ỨNG VỚI NÚT UNCONNECT KHI NHẤN NÚT MORE.
MORE_CONNECT = DROPDOWN_MENU + "//div[contains(@aria-label, 'Remove') and contains(@aria-label, 'connection')]"
# XPATH ỨNG VỚI NÚT PENDING KHI NHẤN NÚT MORE.
MORE_PENDING = DROPDOWN_MENU + "//div[contains(@aria-label, 'Withdraw')]"
# XPATH ỨNG VỚI NÚT ADD A NOTE.
BUTTON_ADD_NOTE = "//button[contains(@aria-label, 'Add a note')]"
# XPATH ỨNG VỚI KHUNG NHẬP NOTE.
TEXTAREA_NOTE = "//textarea[@id='custom-message']"
# XPATH ỨNG VỚI NÚT GỬI NOTE.
BUTTON_SEND_NOTE = "//button[@aria-label='Send now']"
# CSS_SELECTOR ỨNG VỚI NÚT GỬI CONNECT MÀ KHÔNG DÙNG NOTE.
BUTTON_SEND_WITHOUT_NOTE = "button[aria-label*='without a note']"
# XPATH ỨNG VỚI NÚT GỬI CONNECT MÀ DÙNG NOTE.
TEXTFIELD_VERIFY_EMAIL = "//input[@id='email'] | //label[contains(., 'email')]/following-sibling::input"
BUTTON_CONFIRM_EMAIL = "//button[@id='email-confirm'] | //button[contains(@aria-label, 'Verify')]"

"""# **HÀM GỬI KẾT NỐI**"""

def check_status(driver: webdriver.Chrome, xpath: str, *kws):
    try:
        element = WebDriverWait(driver, 2).until(EC.presence_of_element_located((By.XPATH, xpath)))
        status_text = element.get_attribute("aria-label") or ""
        inner_text = element.text or ""

        # Gộp cả 2 text lại
        combined_text = status_text + " " + inner_text

        for keyword in kws:
            if keyword.lower() in combined_text.lower():
                print(f"STATUS: {keyword}")
                return True
    except:
      pass
    return False


def check_status_in_more(driver: webdriver.Chrome):
    # CHECK UNCONNECTED STATUS IN MORE.
    if check_status(driver, MORE_UNCONNECT, "Invite", "Connect"):
        return "Unconnected"
    # CHECK CONNECTED STATUS IN MORE.
    if check_status(driver, MORE_CONNECT, "Remove", "connection"):
        return "Connected"
    # CHECK PENDING STATUS IN MORE.
    if check_status(driver, "//div", "Withdraw", "Pending"):
        return "Pending"
    return "Unknown"  # Giá trị trả về mặc định


def find_element_in_list(driver: webdriver.Chrome, e_list: list[str]):
    for e in e_list:
        try:
            return WebDriverWait(driver, 2).until(EC.presence_of_element_located((By.XPATH, e)))
        except:
          continue
    return None

import random
def send_connection(driver: webdriver.Chrome, xpath: str, email: str):
    try:
        # CLICK BUTTON CONNECT.
        try:
            e = WebDriverWait(driver, 5).until(EC.presence_of_element_located((By.XPATH, xpath)))
            e.click()
        except TimeoutException:
            print("ERROR: BUTTON CONNECT NOT FOUND")
            return "Error"
        except Exception as ex:
            print(f"ERROR: FAILED TO CLICK CONNECT BUTTON: {ex}")
            return "Error"

        # CLICK SEND WITHOUT NOTE.
        try:
            # IT'S WRAPPED IN #SHADOW-HOST (OPEN). WE MUST OPEN IT WITH CSS_SELECTOR INSTEAD
            script = """
                const selector = arguments[0]; // Nhận giá trị từ biến BUTTON_SELECTOR
                    const allElements = document.querySelectorAll('*');
                    for (let el of allElements) {
                        if (el.shadowRoot) {
                            const btn = el.shadowRoot.querySelector(selector);
                            if (btn) {
                                btn.click();
                                return "CLICKED_SHADOW";
                            }
                        }
                    }
                    const normalBtn = document.querySelector(selector);
                    if (normalBtn) {
                        normalBtn.click();
                        return "CLICKED_NORMAL";
                    }
                    return "NOT_FOUND";
            """
            result = driver.execute_script(script, BUTTON_SEND_WITHOUT_NOTE)
            if result != "NOT_FOUND":
                print("SUCCESS: SENT CONNECT WITHOUT NOTE!")
                return "Pending"
        except TimeoutException:
            email_field = driver.find_elements(By.XPATH, TEXTFIELD_VERIFY_EMAIL)
            if email_field and email:
                email_field[0].send_keys(email)
                time.sleep(random.uniform(1, 2))
                verify_btn = driver.find_element(By.XPATH, BUTTON_CONFIRM_EMAIL)
                verify_btn.click()

                time.sleep(2)

                return "Pending"
            print("ERROR: NO SEND BUTTON FOUND!")
            return "Error"
    except Exception as e:
        print(f"\n {e}")
        return "Error"

def check_connection(driver: webdriver.Chrome, email: str, note: str = None):
    try:
        # CHECK PENDING STATUS.
        if check_status(driver, STATUS_PENDING, "Pending", "Sent"):
            print("STATUS: PENDING")
            return "Pending"

        # CHECK UNCONNECTED STATUS.
        if check_status(driver, STATUS_CONNECT, "Invite", "Connect"):
            status = send_connection(driver, STATUS_CONNECT, email)  # Gửi kết nối không có ghi chú
            print(f"STATUS: {status}")
            return status

        # FIND BUTTON MORE.
        print("CHECKING IN MORE", end=" ")
        try:
            button_more = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, BUTTON_MORE)))
            button_more.click()

            # CHECK MORE MENU
            WebDriverWait(driver, 3).until(EC.presence_of_element_located((By.XPATH, DROPDOWN_MENU)))

            status_in_more = check_status_in_more(driver)
            if status_in_more == "Unconnected":
              return send_connection(driver, MORE_UNCONNECT, email)
            elif status_in_more == "Connected":
              return "Connected"
        except TimeoutException:
            driver.save_screenshot("error_more_button.png")
            print("ERROR: BUTTON MORE NOT FOUND!")
            return "ERROR: BUTTON MORE NOT FOUND!"

    except Exception as e:
        print(f"ERROR: {e}")
        return "Error"

def main():
    options = Options()
    options.add_argument('--headless=new')
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-dev-shm-usage')
    options.add_argument('--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36')

    service = Service(ChromeDriverManager().install())
    driver = webdriver.Chrome(service=service, options=options)
    
    try:
        # Lấy data
        df = get_local_data()
        login_with_cookies(driver)
        # Đăng nhập và xử lý
        if df is not None:
            for index, row in df.iterrows():
    # GO TO PROFILE LINK.
                if row['Status'] == 'Unconnected':
                    profile_link = row['LinkedIn']
                    print(f"Visiting profile: {profile_link}", end=" ")
                    driver.get(profile_link)
                    
                    status = ""
                    # Đợi trang tải đầy đủ trước khi kiểm tra kết nối
                    time.sleep(2)

                    try:
                # Wait until page loads
                        time.sleep(random.uniform(3, 5))
                        # Pretend to be reading profile
                        print("Reading profile...", end=" ")
                        time.sleep(random.uniform(5, 10))
                        # Simulate slight scroll down
                        driver.execute_script("window.scrollBy(0, 500);")
                        time.sleep(random.uniform(2, 5))
                        driver.execute_script("window.scrollTo(0, 0);")
                        time.sleep(2)
                        # CHECK CONNECTION AND SEND WITHOUT NOTE.
                        status = check_connection(driver, row["Email"])  # Không gửi ghi chú
                    except Exception as e:
                        print(f"ERROR: {e}")
                        status = "Error"
                        df.at[index, 'Status'] = status
                        print(f"Status: {status}")
                        # UPDATE STATUS IN CSV FILE.
                        df.to_csv('test_data.csv', index=False)
                        

                    # TAKE A BREAK BETWEEN EACH PERSON
                        if index < len(df) - 1:
                            print("Taking a break...", end=" ")
                            driver.get("https://www.linkedin.com")
                            time.sleep(random.randint(30, 60))

    finally:
        driver.quit()
        
if __name__ == "__main__":
    main()