# -*- coding: utf-8 -*-
"""DangQuocThai_ConnectLinkedIn

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12yI9gid3zExhOyT7bhB8JMMJy1PvzThj

# **CÀI ĐẶT THƯ VIỆN CẦN THIẾT**
"""
import os
import time
import base64
import pickle
import pandas as pd
import random
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException, NoSuchElementException
import undetected_chromedriver as uc

def get_driver():
    options = uc.ChromeOptions()
    
    options.add_argument(
        "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/146 Safari/537.36"
    )
    options.add_argument("--headless=new")
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-dev-shm-usage')
    options.add_argument("--window-size=1920,1080")
    options.add_argument("--disable-gpu")
    
    driver = uc.Chrome(options=options, version_main=146)
    return driver

def is_logged_in(driver: webdriver.Chrome):
    """Kiểm tra xem đã đăng nhập thành công chưa bằng cách tìm kiếm phần tử đặc trưng trên trang feed"""
    try:
        WebDriverWait(driver, 5).until(
            EC.presence_of_element_located((By.CLASS_NAME, 'global-nav__me-photo'))
        )
        return True
    except TimeoutException:
        return False
    
def human_type(element, text):
    import random, time
    for char in text:
        element.send_keys(char)
        time.sleep(random.uniform(0.05, 0.2))

def get_local_data():
    file_path = 'data/test_sheet.csv' # Tên file bạn để trong Repo
    if os.path.exists(file_path):
        df = pd.read_csv(file_path)
        # df = pd.read_excel('test_data.xlsx') # Nếu dùng Excel
        print(f"📊 Đã nạp {len(df)} dòng từ file {file_path}")
        return df
    else:
        print("❌ ERROR: Không tìm thấy file dữ liệu!")
        return None
    
def get_cookies_from_env():
    """Lấy cookies đã được mã hóa từ biến môi trường và giải mã nó"""
    encoded_cookies = os.getenv("LINKEDIN_COOKIES")
    if not encoded_cookies:
        print("ERROR: LINKEDIN_COOKIES environment variable not found!")
        return None

    try:
        decoded_bytes = base64.b64decode(encoded_cookies)
        cookies = pickle.loads(decoded_bytes)
        print("INFO: Cookies loaded from environment variable!")
        return cookies
    except Exception as e:
        print(f"ERROR: Failed to decode cookies: {e}")
        return None
    
def get_credentials_from_env():
    """Lấy credentials đã được mã hóa từ biến môi trường và giải mã nó"""
    encoded_cookies = os.getenv("LINKEDIN_CREDENTIALS")
    if not encoded_cookies:
        print("ERROR: LINKEDIN_CREDENTIALS environment variable not found!")
        return None

    try:
        decoded_bytes = base64.b64decode(encoded_cookies)
        cookies = pickle.loads(decoded_bytes)
        print("INFO: Credentials loaded from environment variable!")
        return cookies
    except Exception as e:
        print(f"ERROR: Failed to decode cookies: {e}")
        return None

def save_cookies(driver: webdriver.Chrome, file_name: str = "cookies.pkl"):
    """Lưu cookies vào file"""
    with open(file_name, "wb") as cookies_file:
        pickle.dump(driver.get_cookies(), cookies_file)
    print("INFO: COOKIES SAVED!")


def handle_cookie_acceptance(driver: webdriver.Chrome):
    """Xử lý chấp nhận cookies nếu có"""
    try:
        # Tăng timeout và thử nhiều loại button text thường gặp
        cookie_xpath = "//button[contains(., 'Accept') or contains(., 'Agree') or contains(., 'Cho phép')]"
        accept_btn = WebDriverWait(driver, 5).until(
            EC.element_to_be_clickable((By.XPATH, cookie_xpath))
        )
        accept_btn.click()
        print("INFO: ✅ Cookie banner accepted")
    except:
        print("INFO: ℹ️ No cookie banner detected or already handled")

def handle_code_verification(driver: webdriver.Chrome):
    """Handle 2FA verification - can read from env var in automated mode"""
    try:
        # Tìm trường nhập mã xác thực
        ID_FIELD = "input__email_verification_pin"
        print("[2FA] ⏳ Waiting up to 30s for 2FA field to appear...")
        
        try:
            verification_field = WebDriverWait(driver, 30).until(
                EC.presence_of_element_located((By.ID, ID_FIELD))
            )
        except TimeoutException:
            print("[2FA] ℹ️ No 2FA required for this login.")
            return True
        # Tìm nút submit
        ID_FIELD = "email-pin-submit-button"
        CONDITION = EC.element_to_be_clickable((By.ID, ID_FIELD))
        submit_button = WebDriverWait(driver, 10).until(CONDITION)

        # Try to get code from environment variable first (for automated runs)
        code = os.getenv("LINKEDIN_2FA_CODE")
        
        if not code:
            # If running interactively, ask user
            import sys
            if sys.stdin.isatty():
                code = input("[2FA] Verification code required! Check your email and enter the code: ")
            else:
                print("[2FA] ⚠️ Code required but in automated mode and no LINKEDIN_2FA_CODE env var set")
                print("[2FA] Skipping 2FA - may fail if actually required")
                return False
        
        if code:
            verification_field.send_keys(code)
            time.sleep(1)
            submit_button.click()
            time.sleep(2)
            print("[2FA] ✅ Code submitted")
            return True
            
    except TimeoutException:
        print("[2FA] ℹ️ No 2FA verification detected")
        return True
    except Exception as e:
        print(f"[2FA] ⚠️ Error checking for 2FA: {e}")
        driver.save_screenshot("error_login.png")
        return True


def load_session_with_cookies(driver: webdriver.Chrome) -> bool:
    cookies = get_cookies_from_env()
    
    if not cookies:
        print("[SESSION] ❌ No stored cookies found in environment variables")
        return False
    
    print("[SESSION] 🍪 Attempting stealth injection...")
    
    driver.get("https://www.linkedin.com/")
    time.sleep(3)  # Wait for the page to load
    valid_cookies = []
    
    for cookie in cookies:
        cookie.pop('sameSite', None)
        cookie.pop('expiry', None)  # sometimes breaks injection
        try:
            driver.add_cookie(cookie)
            valid_cookies.append(cookie)
        except Exception as e:
            print(f"[SESSION] ⚠️ Failed to add cookie: {e}")
            continue
        
    print(f"[SESSION] ✅ Injected {len(valid_cookies)}/{len(cookies)} cookies successfully")
    driver.get("https://www.linkedin.com/feed/")
    time.sleep(5)  # Wait for the feed to load
    
    # Check if login was successful by looking for profile avatar
    return is_logged_in(driver)

def login(driver: webdriver.Chrome, username: str, password: str):
    driver.get("https://www.linkedin.com/feed")
    time.sleep(3)

    if is_logged_in(driver):
        print("✅ Already logged in — skipping login")
        return True
    """Đăng nhập vào LinkedIn and save session (first time only)"""
    XPATH_USERNAME = '//*[@id="username"]'
    XPATH_PASSWORD = '//*[@id="password"]'
    XPATH_LOGIN_BUTTON = '//button[contains(@class, "btn__primary--large")]'
    
    print("🔐 Starting LinkedIn login process...")
    driver.get("https://www.linkedin.com/login")
    time.sleep(3)
    
    handle_cookie_acceptance(driver)
    
    driver.save_screenshot("login_page.png")
    
    try: 
        print("⏳ Waiting for login form...")
        username_field = WebDriverWait(driver, 15).until(EC.presence_of_element_located((By.XPATH, XPATH_USERNAME)))
        username_field.click()
        time.sleep(random.uniform(0.5, 1.5))
        human_type(username_field, username)
        if random.random() < 0.2:
            print("⌨️ Oops, retyping username...")
            username_field.clear()
            time.sleep(random.uniform(1, 2))
            human_type(username_field, username)
        time.sleep(random.uniform(1, 2))
        
        
        password_field = WebDriverWait(driver, 15).until(EC.presence_of_element_located((By.XPATH, XPATH_PASSWORD)))
        password_field.click()
        time.sleep(random.uniform(0.5, 1.5))
        human_type(password_field, password)
        if random.random() < 0.2:
            print("⌨️ Oops, retyping password...")
            password_field.clear()
            time.sleep(random.uniform(1, 2))
            human_type(password_field, password)
        time.sleep(random.uniform(1, 2))
        
        print("🤔 Reviewing credentials...")
        time.sleep(random.uniform(2, 4))

        print("🚀 Clicking login button...")
        for _ in range(2):
            login_button = WebDriverWait(driver, 15).until(EC.element_to_be_clickable((By.XPATH, XPATH_LOGIN_BUTTON)))
            login_button.click()
            time.sleep(5)
            handle_code_verification(driver)
            time.sleep(5)
            current_url = driver.current_url

            if "checkpoint" in current_url or "challenge" in current_url:
                print("🚨 LinkedIn triggered verification checkpoint!")
                return False
            
            if is_logged_in(driver):
                print("✅ SUCCESS: ĐĂNG NHẬP THÀNH CÔNG!")
                save_cookies(driver)
                 
                print("🧍 Settling after login...")
                time.sleep(random.uniform(10, 20))

                driver.execute_script("window.scrollBy(0, 300);")
                time.sleep(random.uniform(3, 6))
                driver.execute_script("window.scrollTo(0, 0);")
                time.sleep(random.uniform(2, 5))
                return True

            print("[LOGIN] 🔄 Retry clicking login...")
            time.sleep(random.uniform(2, 4))
    except TimeoutException:
      # Use when the page says Welcome Back instead
      try:
        welcome_button = WebDriverWait(driver, 5).until(
            EC.element_to_be_clickable((By.CSS_SELECTOR, "button.member-profile__details"))
        )

        print("[LOGIN] 🔄 Found an account!")
        welcome_button.click()
        time.sleep(2)

        handle_code_verification(driver)

        time.sleep(5)
        if is_logged_in(driver):
            print("✅ SUCCESS: ĐĂNG NHẬP THÀNH CÔNG!")
            save_cookies(driver)
                
            print("🧍 Settling after login...")
            time.sleep(random.uniform(10, 20))

            driver.execute_script("window.scrollBy(0, 300);")
            time.sleep(random.uniform(3, 6))
            driver.execute_script("window.scrollTo(0, 0);")
            time.sleep(random.uniform(2, 5))
            return True

        save_cookies(driver)

        print("INFO: Login successful! Cookies and credentials saved!")
        return True
      except TimeoutException:
          print(f"ERROR: LOGIN NOT SUCCESSFUL")
          return False
      except: # Now this is genuinely unable to login
        print("ERROR: LOGIN FAILED")
        return False
    except Exception as e:
        print(f"❌ ERROR: Login failed: {e}")
        driver.save_screenshot("login_error.png")
        return False

    
# XPATH ỨNG VỚI NÚT CONNECT (English & Vietnamese)
STATUS_CONNECT = "//main//section[1]//a[contains(@aria-label, 'Invite') or contains(@aria-label, 'Mời') or contains(., 'Connect') or contains(., 'kết nối')]"

# XPATH ỨNG VỚI NÚT PENDING (English & Vietnamese)
STATUS_PENDING = "//main//section[1]//a[contains(., 'Pending') or contains(., 'Đã gửi')]"
# XPATH ỨNG VỚI NÚT MORE.
#BUTTON_MORE = "/html/body/div[5]/div[3]/div/div/div[2]/div/div/main/section[1]/div[2]/div[3]/div/div[2]/button"
BUTTON_MORE = "//main//section[1]//button[contains(., 'More') or contains(., 'Khác')]"
DROPDOWN_MENU = "//div[@role='menu']"
# XPATH ỨNG VỚI NÚT CONNECT KHI NHẤN NÚT MORE (English & Vietnamese)
MORE_UNCONNECT = DROPDOWN_MENU + "//div[(contains(@aria-label, 'Invite') and contains(@aria-label, 'to connect')) or (contains(@aria-label, 'Mời') and contains(@aria-label, 'kết nối'))]"
# XPATH ỨNG VỚI NÚT UNCONNECT KHI NHẤN NÚT MORE (English & Vietnamese)
MORE_CONNECT = DROPDOWN_MENU + "//div[(contains(@aria-label, 'Remove') and contains(@aria-label, 'connection')) or contains(@aria-label, 'Xóa kết nối')]"
# XPATH ỨNG VỚI NÚT PENDING KHI NHẤN NÚT MORE (English & Vietnamese)
MORE_PENDING = DROPDOWN_MENU + "//div[contains(@aria-label, 'Withdraw') or contains(@aria-label, 'Hủy yêu cầu')]"
# XPATH ỨNG VỚI NÚT ADD A NOTE.
BUTTON_ADD_NOTE = "//button[contains(@aria-label, 'Add a note')]"
# XPATH ỨNG VỚI KHUNG NHẬP NOTE.
TEXTAREA_NOTE = "//textarea[@id='custom-message']"
# XPATH ỨNG VỚI NÚT GỬI NOTE.
BUTTON_SEND_NOTE = "//button[@aria-label='Send now']"
# CSS_SELECTOR ỨNG VỚI NÚT GỬI CONNECT MÀ KHÔNG DÙNG NOTE.
BUTTON_SEND_WITHOUT_NOTE = "button[aria-label*='without a note']"
# XPATH ỨNG VỚI NÚT GỬI CONNECT MÀ DÙNG NOTE.
TEXTFIELD_VERIFY_EMAIL = "//input[@id='email'] | //label[contains(., 'email')]/following-sibling::input"
BUTTON_CONFIRM_EMAIL = "//button[@id='email-confirm'] | //button[contains(@aria-label, 'Verify')]"

"""# **HÀM GỬI KẾT NỐI**"""

def check_status(driver: webdriver.Chrome, xpath: str, *kws):
    try:
        element = WebDriverWait(driver, 2).until(EC.presence_of_element_located((By.XPATH, xpath)))
        status_text = element.get_attribute("aria-label") or ""
        inner_text = element.text or ""

        # Gộp cả 2 text lại
        combined_text = status_text + " " + inner_text

        for keyword in kws:
            if keyword.lower() in combined_text.lower():
                print(f"STATUS: {keyword}")
                return True
    except:
      pass
    return False


def check_status_in_more(driver: webdriver.Chrome):
    # CHECK UNCONNECTED STATUS IN MORE (English & Vietnamese).
    if check_status(driver, MORE_UNCONNECT, "Invite", "Connect", "Mời", "kết nối"):
        return "Unconnected"
    # CHECK CONNECTED STATUS IN MORE (English & Vietnamese).
    if check_status(driver, MORE_CONNECT, "Remove", "connection", "Xóa", "kết nối"):
        return "Connected"
    # CHECK PENDING STATUS IN MORE (English & Vietnamese).
    if check_status(driver, "//div", "Withdraw", "Pending", "Hủy", "Đã gửi"):
        return "Pending"
    return "Unknown"  # Giá trị trả về mặc định


def find_element_in_list(driver: webdriver.Chrome, e_list: list[str]):
    for e in e_list:
        try:
            return WebDriverWait(driver, 2).until(EC.presence_of_element_located((By.XPATH, e)))
        except:
          continue
    return None
def send_connection(driver: webdriver.Chrome, xpath: str, email: str):
    try:
        # CLICK BUTTON CONNECT.
        try:
            e = WebDriverWait(driver, 5).until(EC.presence_of_element_located((By.XPATH, xpath)))
            e.click()
        except TimeoutException:
            print("ERROR: BUTTON CONNECT NOT FOUND")
            return "Error"
        except Exception as ex:
            print(f"ERROR: FAILED TO CLICK CONNECT BUTTON: {ex}")
            return "Error"

        # CLICK SEND WITHOUT NOTE.
        try:
            # IT'S WRAPPED IN #SHADOW-HOST (OPEN). WE MUST OPEN IT WITH CSS_SELECTOR INSTEAD
            script = """
                const selector = arguments[0]; // Nhận giá trị từ biến BUTTON_SELECTOR
                    const allElements = document.querySelectorAll('*');
                    for (let el of allElements) {
                        if (el.shadowRoot) {
                            const btn = el.shadowRoot.querySelector(selector);
                            if (btn) {
                                btn.click();
                                return "CLICKED_SHADOW";
                            }
                        }
                    }
                    const normalBtn = document.querySelector(selector);
                    if (normalBtn) {
                        normalBtn.click();
                        return "CLICKED_NORMAL";
                    }
                    return "NOT_FOUND";
            """
            result = driver.execute_script(script, BUTTON_SEND_WITHOUT_NOTE)
            if result != "NOT_FOUND":
                print("SUCCESS: SENT CONNECT WITHOUT NOTE!")
                return "Pending"
        except TimeoutException:
            email_field = driver.find_elements(By.XPATH, TEXTFIELD_VERIFY_EMAIL)
            if email_field and email:
                email_field[0].send_keys(email)
                time.sleep(random.uniform(1, 2))
                verify_btn = driver.find_element(By.XPATH, BUTTON_CONFIRM_EMAIL)
                verify_btn.click()

                time.sleep(2)

                return "Pending"
            print("ERROR: NO SEND BUTTON FOUND!")
            return "Error"
    except Exception as e:
        print(f"\n {e}")
        return "Error"

def check_connection(driver: webdriver.Chrome, email: str, note: str = None):
    try:
        # CHECK PENDING STATUS (English & Vietnamese).
        if check_status(driver, STATUS_PENDING, "Pending", "Đã gửi"):
            print("STATUS: PENDING")
            return "Pending"

        # CHECK UNCONNECTED STATUS (English & Vietnamese).
        if check_status(driver, STATUS_CONNECT, "Invite", "Connect", "Mời", "kết nối"):
            status = send_connection(driver, STATUS_CONNECT, email)
            print(f"STATUS: {status}")
            return status

        # FIND BUTTON MORE.
        print("CHECKING IN MORE", end=" ")
        try:
            button_more = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, BUTTON_MORE)))
            button_more.click()

            # CHECK MORE MENU
            WebDriverWait(driver, 3).until(EC.presence_of_element_located((By.XPATH, DROPDOWN_MENU)))

            status_in_more = check_status_in_more(driver)
            if status_in_more == "Unconnected":
              return send_connection(driver, MORE_UNCONNECT, email)
            elif status_in_more == "Connected":
              return "Connected"
        except TimeoutException:
            driver.save_screenshot("error_more_button.png")
            print("ERROR: BUTTON MORE NOT FOUND!")
            return "ERROR: BUTTON MORE NOT FOUND!"

    except Exception as e:
        print(f"ERROR: {e}")
        return "Error"

def main():
    # Take a random break at the start to avoid being detected as a bot if running on a schedule
    time.sleep(random.randint(60, 1800))
    
    driver = get_driver()
    
    try:
        # Get data from CSV
        df = get_local_data()
        if df is None:
            print("[CRON] ❌ ERROR: Could not load data file")
            return False
        
        # Get credentials from environment variables
        username = os.getenv("LINKEDIN_USERNAME")
        password = os.getenv("LINKEDIN_PASSWORD")
        
        if not username or not password:
            print("[CRON] ❌ ERROR: LINKEDIN_USERNAME and LINKEDIN_PASSWORD environment variables are required!")
            return False
        
        # Step 1: Try to use existing session with cookies (safest approach)
        print("[CRON] 🔄 Attempting to restore session with cookies...")
        if load_session_with_cookies(driver):
            print("[CRON] ✅ Using cached session - no fresh login needed")
        else:
            # Step 2: If cookies failed, do a fresh login (will update cookies)
            print("[CRON] 🔐 Cookies invalid/missing. Doing fresh login...")
            if not login(driver, username, password):
                print("[CRON] ❌ Failed to login. Exiting...")
                return False
            print("[CRON] ✅ Successfully logged in and cookies saved!")
        
        print("[CRON] ✅ Ready to send connections")
        
        count = 0 
        limit = 15 # LinkedIn có giới hạn gửi kết nối, thường là 15/ngày.
        
    # GO TO PROFILE LINK.
        for index, row in df.iterrows():
            # Dừng lại nếu đã đạt đến giới hạn gửi kết nối
            if count >= limit:
                print(f"[CRON] ⏹️ Reached daily connection limit ({limit}). Stopping.")
                break
            # Chỉ xử lý những người có trạng thái Unconnected
            if row['Status'] == 'Unconnected':
                profile_link = row['LinkedIn']
                print(f"[CRON] 👤 Visiting profile: {profile_link}", end=" ")
                driver.get(profile_link)
                
                status = ""
                
                try:
                    # Wait until page loads
                    time.sleep(random.uniform(3, 5))
                    # Pretend to be reading profile
                    print("Reading...", end=" ")
                    time.sleep(random.uniform(5, 10))
                    # Simulate slight scroll down
                    driver.execute_script("window.scrollBy(0, 500);")
                    time.sleep(random.uniform(2, 5))
                    driver.execute_script("window.scrollTo(0, 0);")
                    time.sleep(2)
                    # CHECK CONNECTION AND SEND WITHOUT NOTE.
                    status = check_connection(driver, row["Email"])
                    count += 1
                    df.at[index, 'Status'] = status
                    print(f"✅ Status: {status}")
                    
                except Exception as e:
                    print(f"❌ ERROR: {e}")
                    status = "Error"
                    df.at[index, 'Status'] = status
                
                # UPDATE STATUS IN CSV FILE
                df.to_csv('data/test_sheet.csv', index=False)
                
                # TAKE A BREAK BETWEEN EACH PERSON
                if index < len(df) - 1:
                    print("[CRON] ⏳ Taking a break...", end=" ")
                    time.sleep(random.uniform(30, 60))
                    print("Done")
        
        print(f"[CRON] ✅ COMPLETED: Sent {count} connection requests")
        return True
        
    except Exception as e:
        print(f"[CRON] ❌ CRITICAL ERROR: {e}")
        import traceback
        traceback.print_exc()
        return False
        
    finally:
        driver.quit()
        
if __name__ == "__main__":
    success = main()
    exit(0 if success else 1)  # Exit with status code for cron-job.org