name: LinkedIn Auto Run
on:
  repository_dispatch:
    types: [trigger-linkedin]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: pip install selenium webdriver-manager pandas
      - name: Run Script
        run: python3 main.py
        env:
          LINKEDIN_USERNAME: ${{ secrets.LINKEDIN_USERNAME }}
          LINKEDIN_PASSWORD: ${{ secrets.LINKEDIN_PASSWORD }}
          LINKEDIN_COOKIES: ${{ secrets.LINKEDIN_COOKIES }}
      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/test_sheet.csv
          git commit -m "Update LinkedIn connection status [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Logs and Cookies
        uses: actions/upload-artifact@v4
        if: always() # Luôn chạy kể cả khi script bị lỗi
        with:
          name: bot-debug-data
          path: |
            *.png
            *.pkl
            data/test_sheet.csv